version: '3.8'

services:
  testtask_retail:
    build: ./
    command: ./wait-for-postgres.sh db ./testtask_retail
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=admin


  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5435:5432
